export const KarenHayesTxData = [
  {
    txName: "Jabari Willie Johnson",
    whatUsed: "Pending",
    credit: "+$160,000.00",
    date: "Sept 01, 2023",
    color: "green",
  },
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2023",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "May 05, 2023",
    color: "red",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2023",
    color: "red",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2023",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];

export const StephanieSarahJensenTxData = [
  {
    txName: "Apparel Production Inc.",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2023",
    color: "green",
  },
  {
    txName: "Call To Action Clothing",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2023",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2023",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2023",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Jan 1, 2023",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "Dec 29, 2022",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Dec 18, 2022",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Dec 16, 2022",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];

export const JohnIrwinTxData = [
  {
    txName: "Apparel Production Inc.",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2023",
    color: "green",
  },
  {
    txName: "Call To Action Clothing",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2023",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2023",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2023",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Jan 1, 2023",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "Dec 29, 2022",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Dec 18, 2022",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Dec 16, 2022",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];

export const HarleyRollinTxData = [
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+$500,000.00",
    date: "Aug 22, 2023",
    color: "green",
  },
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+$500,000.00",
    date: "Aug 22, 2023",
    color: "green",
  },
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+$518,705.25",
    date: "Aug 22, 2023",
    color: "green",
  },
  {
    txName: "VAT",
    whatUsed: "Debit",
    debit: "-$9,928.72",
    date: "Aug 22, 2023",
    color: "red",
  },
  {
    txName: "VAT Reversed",
    whatUsed: "Credit",
    credit: "+$9,928.72",
    date: "Aug 22, 2023",
    color: "green",
  },
  {
    txName: "Inheritance funds",
    whatUsed: "Credit",
    credit: "+$225,000.00",
    date: "Aug 16, 2023",
    color: "green",
  },
];

export const JackThomasLedBetterTxData = [
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+$500,000.00",
    date: "Aug 5, 2023",
    color: "green",
  },
  {
    txName: "Interest",
    whatUsed: "Credit",
    credit: "+$17,000.00",
    date: "Apr 15, 2023",
    color: "green",
  },
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+$500,000.00",
    date: "Mar 25, 2023",
    color: "green",
  },
  {
    txName: "Zelle Payment from Terry Lance",
    whatUsed: "Credit",
    credit: "+$2000.00",
    date: "Mar 15, 2023",
    color: "green",
  },
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+$518,705.25",
    date: "Mar 9, 2023",
    color: "green",
  },
  {
    txName: "Payroll",
    whatUsed: "Credit",
    credit: "+$19,928.72",
    date: "Feb 22, 2023",
    color: "green",
  },
  {
    txName: "VAT Reversed",
    whatUsed: "Credit",
    credit: "+$9,928.72",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "VAT",
    whatUsed: "Debit",
    debit: "-$9,928.72",
    date: "Feb 10, 2023",
    color: "red",
  },
  {
    txName: "Inheritance funds",
    whatUsed: "Credit",
    credit: "+$225,000.00",
    date: "Feb 2, 2023",
    color: "green",
  },
];

export const MorganRisseTxData = [
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2023",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "May 05, 2023",
    color: "red",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2023",
    color: "red",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2023",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];
export const GeorgeRobertMullingTxData = [
  {
    txName: "West Company",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2023",
    color: "green",
  },
  {
    txName: "Total Station",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Presto Fresco",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2023",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "May 05, 2023",
    color: "red",
  },
  {
    txName: "Tech Invest",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2023",
    color: "red",
  },
  {
    txName: "Anna Emily",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "Williams Charles",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2023",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];
export const SherrandaDionnePattonTxData = [
  {
    txName: "Grant",
    whatUsed: "Credit",
    debit: "+$80,000.00",
    date: "Sept 25, 2023",
    color: "green",
  },
  {
    txName: "Low income",
    whatUsed: "Credit",
    debit: "+$30,000.00",
    date: "Sept 25, 2023",
    color: "green",
  },
  {
    txName: "New year and Christmas",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Sept 25, 2023",
    color: "green",
  },
  {
    txName: "Appeal bonus",
    whatUsed: "Credit",
    debit: "+$10,000.00",
    date: "Sept 25, 2023",
    color: "green",
  },
  {
    txName: "Additional fees",
    whatUsed: "Credit",
    debit: "+$35,000.00",
    date: "Sept 24, 2023",
    color: "green",
  },
  {
    txName: "Delay fees",
    whatUsed: "Credit",
    debit: "+$15,000.00",
    date: "Sept 24, 2023",
    color: "green",
  },
  {
    txName: "New year and Christmas",
    whatUsed: "Credit",
    debit: "+$80,000.00",
    date: "Sept 24, 2023",
    color: "green",
  },
];

export const GeorgeCarrieLillyTxData = [
  {
    txName: "Apparel Production Inc.",
    whatUsed: "Credit",
    debit: "+$125,000.00",
    date: "Jun 04, 2023",
    color: "green",
  },
  {
    txName: "Call To Action Clothing",
    whatUsed: "Credit",
    debit: "+$75,000.00",
    date: "Jun 25, 2023",
    color: "green",
  },
  {
    txName: "Etfashion",
    whatUsed: "Credit",
    debit: "+$200,000.00",
    date: "Jun 19, 2023",
    color: "green",
  },
  {
    txName: "Headquarters Construction",
    whatUsed: "Debit",
    debit: "-$75,000.00",
    date: "Jun 04, 2023",
    color: "red",
  },
  {
    txName: "Gebbers Farms",
    whatUsed: "Credit",
    debit: "+$500,000.00",
    date: "May 05, 2023",
    color: "green",
  },
  {
    txName: "Busch Agricultural Resources",
    whatUsed: "Credit",
    debit: "+$50,000.00",
    date: "May 01, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$400,000.00",
    date: "Apr 25, 2023",
    color: "red",
  },
  {
    txName: "Farm.One",
    whatUsed: "Credit",
    debit: "+$85,000.00",
    date: "Mar 03, 2023",
    color: "green",
  },
  {
    txName: "IJH FARM",
    whatUsed: "Credit",
    debit: "+$150,000.00",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Jan 15, 2023",
    color: "red",
  },
  {
    txName: "Summit Agricultural Group",
    whatUsed: "Credit",
    debit: "+$135,000.00",
    date: "Jan 1, 2023",
    color: "green",
  },
  {
    txName: "Follow Suit Swimwear",
    whatUsed: "credit",
    debit: "+$195,000.00",
    date: "Dec 29, 2022",
    color: "green",
  },
  {
    txName: "Brunt Workwear",
    whatUsed: "credit",
    debit: "+$92,280.00",
    date: "Dec 21, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$237,350.00",
    date: "Dec 18, 2022",
    color: "red",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$40,000.00",
    date: "Dec 16, 2022",
    color: "red",
  },
  {
    txName: "Prestage Farms of Iowa",
    whatUsed: "Credit",
    debit: "+$100,000.00",
    date: "Dec 08, 2022",
    color: "green",
  },
  {
    txName: "Cash Withdrawal",
    whatUsed: "Debit",
    debit: "-$500,000.00",
    date: "Dec 04, 2022",
    color: "red",
  },
];