const users = [
  { 
    id: 1,
    name: "Karen Hayes",
    cardName: "Karen Hayes ",
    username: "Loveyoujimmy1@",
    password: "SuccessfullHayes111@",
    amount: "2,100,000.00",
    savingAccountName: "Jimmie E Clay",
    savingAccountAmount: "1,020,000.00",
  },
  { 
    id: 2,
    name: "Stephanie Sarah Jensen",
    cardName: "Stephanie Sarah J.",
    username: "Driver29",
    password: "Billycompany3048",
    amount: "2,586,094.00",
  },
  { 
    id: 3,
    name: "John Irwin",
    cardName: "John Irwin",
    username: "JohnSavings",
    password: "Jackson1993",
    amount: "25,000,000.00",
  },
  { 
    id: 4,
    name: "Harley Rollins",
    cardName: "Harley Rollins",
    username: "Harleyrollins",
    password: "Harleyrollins123",
    amount: "1,743,705.25",
  },
  { 
    id: 5,
    name: "George Carrie Lilly",
    cardName: "George Carrie L.",
    username: "Georgelilly",
    password: "Carrie$$00",
    amount: "50,000,000.00",
  },
  { 
    id: 6,
    name: "JACK THOMAS LEDBETTER",
    cardName: "JACK THOMAS L.",
    username: "Jbedletter0055",
    password: "1955",
    amount: "21,386,880.00",
  },
  { 
    id: 7,
    name: "MORGAN RISSE",
    cardName: "MORGAN RISSE",
    username: "Morgan790M",
    password: "Morgan123$",
    amount: "1,000,000.00",
  },
  { 
    id: 8,
    name: "George Robert Mulling",
    cardName: "George Robert M.",
    username: "GeorgeRobertMulling",
    password: "96371055",
    amount: "50,000,000.00",
  },
  { 
    id: 9,
    name: "Sherranda Dionne Patton",
    cardName: "Sherranda Dionne P.",
    username: "Sherranda123",
    password: "SherrandaD#50",
    amount: "350,000.00",
  },
  { 
    id: 10,
    name: "Susan Nicholson",
    cardName: "Susan Nicholson",
    username: "Susan Nicholson",
    password: "Nicholson",
    amount: "50,000,000.00",
  },
  { 
    id: 11,
    name: "Hendrix Edward Billy",
    cardName: "Hendrix Edward B.",
    username: "Hendrixedwardbilly",
    password: "Hendrixbill10",
    amount: "99,000,000.00",
  },
];
export default users;